//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fotos_publ_anfitrion
    {
        public int idfotos_publ_anfitrion { get; set; }
        public string nombre { get; set; }
        public string ruta_multimedia { get; set; }
        public int idpublicacion_Anfitrion { get; set; }
    
        public virtual publicacion_anfitrion publicacion_anfitrion { get; set; }
    }
}
