//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WantgoProdEntities : DbContext
    {
        public WantgoProdEntities()
            : base("name=WantgoProdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JwtParametros> JwtParametros { get; set; }
        public virtual DbSet<table_jwt> table_jwt { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<preferencias> preferencias { get; set; }
        public virtual DbSet<preferencias_categoria> preferencias_categoria { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<experiencia> experiencia { get; set; }
        public virtual DbSet<usuario_experiencia> usuario_experiencia { get; set; }
        public virtual DbSet<contacto_emergencia> contacto_emergencia { get; set; }
        public virtual DbSet<comentarios> comentarios { get; set; }
        public virtual DbSet<curiosidades> curiosidades { get; set; }
        public virtual DbSet<emociones> emociones { get; set; }
        public virtual DbSet<experiencia_emociones> experiencia_emociones { get; set; }
        public virtual DbSet<fotos_publ_anfitrion> fotos_publ_anfitrion { get; set; }
        public virtual DbSet<notificacion> notificacion { get; set; }
        public virtual DbSet<preferencias_usuario> preferencias_usuario { get; set; }
        public virtual DbSet<publicacion_anfitrion> publicacion_anfitrion { get; set; }
        public virtual DbSet<seguimiento_usuario_pais> seguimiento_usuario_pais { get; set; }
        public virtual DbSet<servicios> servicios { get; set; }
        public virtual DbSet<servicios_publicacion_anfitrion> servicios_publicacion_anfitrion { get; set; }
        public virtual DbSet<tipo_perfil> tipo_perfil { get; set; }
        public virtual DbSet<PerfilesxUsuario> PerfilesxUsuario { get; set; }
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<conexiones> conexiones { get; set; }
    }
}
