//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil
    {
        public int id_perfil { get; set; }
        public string nombre_usuario { get; set; }
        public string apellido_usuario { get; set; }
        public string descripcion { get; set; }
        public string cedula { get; set; }
        public string rh { get; set; }
        public string ciudad_nacimiento { get; set; }
        public string ocupacion { get; set; }
        public string idiomas { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string numero_pasaporte { get; set; }
        public string pdf_cedula { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
