//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicacion_anfitrion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public publicacion_anfitrion()
        {
            this.fotos_publ_anfitrion = new HashSet<fotos_publ_anfitrion>();
            this.servicios_publicacion_anfitrion = new HashSet<servicios_publicacion_anfitrion>();
        }
    
        public int idpublicacion_Anfitrion { get; set; }
        public string frase_representiva { get; set; }
        public System.DateTime fecha_publicacion { get; set; }
        public int valor_por_noche { get; set; }
        public string lat_lon { get; set; }
        public string ciudad { get; set; }
        public Nullable<int> valor_Huesped_Adicional { get; set; }
        public int id_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fotos_publ_anfitrion> fotos_publ_anfitrion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicios_publicacion_anfitrion> servicios_publicacion_anfitrion { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
