//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicios_publicacion_anfitrion
    {
        public int id_servicios_publicacion_anfitrion { get; set; }
        public string calificacion_servicio { get; set; }
        public int id_Servicios { get; set; }
        public int idpublicacion_Anfitrion { get; set; }
    
        public virtual publicacion_anfitrion publicacion_anfitrion { get; set; }
        public virtual servicios servicios { get; set; }
    }
}
