//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_experiencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario_experiencia()
        {
            this.curiosidades = new HashSet<curiosidades>();
        }
    
        public int idUsuario_Experiencia { get; set; }
        public int id_usuario { get; set; }
        public int id_Experiencia { get; set; }
    
        public virtual experiencia experiencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<curiosidades> curiosidades { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
